Fix Redux store context for Layer
zooniverse/classroom pull request #331
Opened 2022-05-16 09:17 UTC by eatyourgreens

Wrap the connected assignment form and classroom form in `Layer`. This makes sure that the Redux store context is passed down correctly to the layer contents.

Closes #325.

2022-05-16 17:44 UTC, mcbouslog commented
When on https://localhost:3998/#/astro-101-with-galaxy-zoo/educators/ signed in with my staging user, should I be able to click the "Create New Classroom" button or is there additional settings my user needs? At the moment, the button is disabled for me.

2022-05-17 11:56 UTC, shaunanoordin commented
I'm popping into this for a bit to debug that mysterious "disabled Create New Classroom" button. I'll report findings shortly.

2022-05-17 13:57 UTC, shaunanoordin commented
Good news, this is a simple fix 👌 

- The "Create New Classroom" button is disabled because its onClick prop is `undefined`
- The onClick prop is undefined because, in this PR, the `ClassroomManager.props.toggleFormVisibility` value is undefined.
- This, in turn, is because this line in `ClassroomsManager.jsx`'s `ClassroomManager.defaultProps` was removed: `toggleFormVisibility: Actions.classrooms.toggleFormVisibility`

Re-adding that _Actions.classrooms.toggleFormVisibility_ line to _ClassroomManager.defaultProps_ should solve the problem. 👍

2022-05-17 15:29 UTC, mcbouslog requested changes
Thanks @shaunanoordin ! I confirmed your suggestion fixes my noted issue.

2022-05-17 15:30 UTC, mcbouslog approved these changes
Thanks @eatyourgreens ! Sorry I missed your commit a few minutes ago.

2022-05-17 15:34 UTC, eatyourgreens commented
Joining a classroom is broken, but that's because the token is in the URL fragment, not the query string.

2022-05-17 15:35 UTC, eatyourgreens commented
`joinToken` might be broken on master though, and not related to this PR.

2022-05-17 15:58 UTC, merged